import Head from 'next/head'
import Navbar from '@/Components/Navbar'
import Content from '@/Components/Content';
import Hero from '@/Components/Hero';
import Feature from '@/Components/Feature';
import Banner from '@/Components/Banner';


export default function Home() {
  return (
    <>
      <Head>
        <title>Gym Baran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={`bg-gradient-to-r from-[#F9EBF4] to-[#f7f4f8] bg-center w-full bg-cover`}>
          <Navbar />
          <Banner />
        </div>
        <Content />
        <Hero />
        <Feature />
      </main>
    </>
  )
}
